/**
 * Simpero Compliance Framework Registry
 *
 * Each framework is a data module defining:
 *  - id: machine-readable key
 *  - name: display name
 *  - shortName: badge label
 *  - jurisdiction: geographic scope
 *  - primaryTarget: who this framework governs
 *  - description: one-line summary
 *  - relevantFlagCategories: governance flag categories this framework cares about
 *  - thresholds: scorecard thresholds (unverified claims + H-severity flags)
 *  - attestationLabel: what the principal is attesting to under this framework
 *  - pdfDisclaimer: disclaimer paragraph for the PDF cover page
 *  - citationRef: authoritative citation string
 *
 * Architecture: the pipeline computes a FrameworkResult for each framework
 * independently. The MemoViewer shows a badge per framework. The PDF shows
 * a compliance matrix table on the cover page.
 */

export type ComplianceStatus = "COMPLIANT" | "REVIEW_REQUIRED" | "NON_COMPLIANT";

export interface FrameworkThresholds {
  /** Max unverified claims to be COMPLIANT */
  compliantMaxUnverified: number;
  /** Max H-severity flags to be COMPLIANT */
  compliantMaxHFlags: number;
  /** Max unverified claims to be REVIEW_REQUIRED (above this = NON_COMPLIANT) */
  reviewMaxUnverified: number;
  /** Max H-severity flags to be REVIEW_REQUIRED (above this = NON_COMPLIANT) */
  reviewMaxHFlags: number;
}

export interface ComplianceFramework {
  id: string;
  name: string;
  shortName: string;
  jurisdiction: "US" | "CA" | "EU" | "GLOBAL";
  primaryTarget: string;
  description: string;
  relevantFlagCategories: string[];
  thresholds: FrameworkThresholds;
  attestationLabel: string;
  pdfDisclaimer: string;
  citationRef: string;
}

export interface FrameworkResult {
  frameworkId: string;
  shortName: string;
  status: ComplianceStatus;
  relevantFlags: number;
  relevantHFlags: number;
}

// ---------------------------------------------------------------------------
// Framework Definitions
// ---------------------------------------------------------------------------

/**
 * FINRA Rule 3110 — Written Supervisory Procedures
 * Target: US broker-dealers and placement agents
 * The highest-specificity, most operationally demanding supervisory standard.
 * Satisfying FINRA 3110 automatically satisfies SEC 206(4)-7.
 */
export const FINRA_3110: ComplianceFramework = {
  id: "finra_3110",
  name: "FINRA Rule 3110",
  shortName: "FINRA 3110",
  jurisdiction: "US",
  primaryTarget: "US broker-dealers and placement agents",
  description:
    "Broker-dealer written supervisory procedures for AI-generated communications; pair with SEC 206(4)-7 for RIA principal-review programs.",
  relevantFlagCategories: [
    "Key-Person Risk",
    "Missing Audited Financials",
    "Sanctions & AML Exposure",
    "Financial Disclosure Quality",
    "Related-Party Transactions",
    "Customer Concentration Risk",
    "Intellectual Property Risk",
    "Missing Forward-Looking Disclosures",
  ],
  thresholds: {
    compliantMaxUnverified: 0,
    compliantMaxHFlags: 0,
    reviewMaxUnverified: 5,
    reviewMaxHFlags: 2,
  },
  attestationLabel: "FINRA Rule 3110(b)(2) Written Supervisory Review",
  pdfDisclaimer:
    "Under FINRA Rule 3110(b)(2), a registered principal must review and attest to this document before it is relied upon for any investment decision. Every factual claim is linked to a verbatim source citation; unverified claims are explicitly flagged and must be independently verified before distribution.",
  citationRef: "FINRA Rule 3110(b)(2)",
};

/**
 * SEC Rule 206(4)-7 — AI Compliance Programs for Registered Investment Advisers
 * Target: SEC-registered investment advisers (PE funds, VC funds, hedge funds)
 * Primary framework for Simpero's core ICP. Less prescriptive than FINRA 3110
 * but directly applicable to PE/VC fund managers.
 */
export const SEC_206_4_7: ComplianceFramework = {
  id: "sec_206_4_7",
  name: "SEC Rule 206(4)-7",
  shortName: "SEC 206(4)-7",
  jurisdiction: "US",
  primaryTarget: "SEC-registered investment advisers (PE, VC, hedge funds)",
  description: "AI compliance program documentation requirements for registered investment advisers.",
  relevantFlagCategories: [
    "Key-Person Risk",
    "Missing Audited Financials",
    "Financial Disclosure Quality",
    "Related-Party Transactions",
    "Customer Concentration Risk",
    "Missing Forward-Looking Disclosures",
  ],
  thresholds: {
    // SEC 206(4)-7 is less prescriptive — allows up to 2 unverified claims and 1 H-flag
    compliantMaxUnverified: 2,
    compliantMaxHFlags: 1,
    reviewMaxUnverified: 8,
    reviewMaxHFlags: 3,
  },
  attestationLabel: "SEC Rule 206(4)-7 Principal Review — AI Compliance Program",
  pdfDisclaimer:
    "This document was generated by an AI system. Under SEC Rule 206(4)-7, registered investment advisers are required to document AI use in their compliance frameworks and ensure human oversight of AI-generated investment analysis. This memo has been reviewed by a registered principal as part of the adviser's AI compliance program.",
  citationRef: "SEC Rule 206(4)-7; SEC AI Task Force 2025 Compliance Plan",
};

/**
 * OSFI E-23 — Model Risk Management
 * Target: Canadian federally regulated financial institutions (FRFIs) and
 *         funds with Canadian institutional LPs
 * Effective: January 2025 (full implementation expected 2027)
 */
export const OSFI_E23: ComplianceFramework = {
  id: "osfi_e23",
  name: "OSFI Guideline E-23",
  shortName: "OSFI E-23",
  jurisdiction: "CA",
  primaryTarget: "Canadian FRFIs and funds with Canadian institutional LPs",
  description: "Model risk management guideline requiring documentation, validation, and governance of AI/ML models.",
  relevantFlagCategories: [
    "Missing Audited Financials",
    "Financial Disclosure Quality",
    "Key-Person Risk",
    "Data Privacy & GDPR",
  ],
  thresholds: {
    // OSFI E-23 focuses on model documentation quality — moderate thresholds
    compliantMaxUnverified: 3,
    compliantMaxHFlags: 1,
    reviewMaxUnverified: 10,
    reviewMaxHFlags: 3,
  },
  attestationLabel: "OSFI E-23 Model Risk Review — AI Governance Attestation",
  pdfDisclaimer:
    "This document was generated by an AI model subject to OSFI Guideline E-23 model risk management requirements. The model has been validated for intended use, limitations have been documented, and human oversight has been applied. This review satisfies OSFI E-23 requirements for model governance documentation applicable to Canadian federally regulated financial institutions.",
  citationRef: "OSFI Guideline E-23 (Model Risk Management, effective January 2025)",
};

/**
 * EU AI Act — High-Risk AI System Documentation
 * Target: Funds with EU-nexus deals, EU portfolio companies, EU institutional LPs
 * Relevant articles: Art. 9 (Risk Management), Art. 13 (Transparency),
 *                    Art. 14 (Human Oversight), Annex I (High-Risk Classification)
 * Effective: August 2026 (full enforcement)
 */
export const EU_AI_ACT: ComplianceFramework = {
  id: "eu_ai_act",
  name: "EU AI Act",
  shortName: "EU AI Act",
  jurisdiction: "EU",
  primaryTarget: "Funds with EU-nexus deals or EU institutional LPs",
  description: "High-risk AI system documentation, transparency, and human oversight requirements.",
  relevantFlagCategories: [
    "Data Privacy & GDPR",
    "Intellectual Property Risk",
    "Missing Forward-Looking Disclosures",
    "Financial Disclosure Quality",
  ],
  thresholds: {
    // EU AI Act emphasises transparency and human oversight — strict on data/privacy flags
    compliantMaxUnverified: 2,
    compliantMaxHFlags: 0,
    reviewMaxUnverified: 6,
    reviewMaxHFlags: 2,
  },
  attestationLabel: "EU AI Act Art. 14 Human Oversight Review",
  pdfDisclaimer:
    "This document was generated by an AI system classified as high-risk under EU AI Act Annex I. In accordance with Articles 9, 13, and 14, this system has undergone risk management assessment, transparency documentation has been prepared, and a qualified human reviewer has exercised meaningful oversight before this output is relied upon. This review satisfies EU AI Act human oversight requirements for AI-assisted investment analysis.",
  citationRef: "EU AI Act Art. 9, 13, 14; Annex I (Regulation (EU) 2024/1689)",
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const ALL_FRAMEWORKS: ComplianceFramework[] = [
  FINRA_3110,
  SEC_206_4_7,
  OSFI_E23,
  EU_AI_ACT,
];

export const FRAMEWORK_MAP: Record<string, ComplianceFramework> = Object.fromEntries(
  ALL_FRAMEWORKS.map((f) => [f.id, f])
);

// ---------------------------------------------------------------------------
// Scorecard Computation
// ---------------------------------------------------------------------------

/**
 * Compute a FrameworkResult for a single framework given the memo's scorecard data.
 */
export function computeFrameworkResult(
  framework: ComplianceFramework,
  unverifiedCount: number,
  governanceFlags: Array<{ category: string; severity: "H" | "M" | "L" }>
): FrameworkResult {
  const relevantFlags = governanceFlags.filter((f) =>
    framework.relevantFlagCategories.includes(f.category)
  );
  const relevantHFlags = relevantFlags.filter((f) => f.severity === "H").length;

  const { thresholds } = framework;
  let status: ComplianceStatus;

  if (
    unverifiedCount <= thresholds.compliantMaxUnverified &&
    relevantHFlags <= thresholds.compliantMaxHFlags
  ) {
    status = "COMPLIANT";
  } else if (
    unverifiedCount <= thresholds.reviewMaxUnverified &&
    relevantHFlags <= thresholds.reviewMaxHFlags
  ) {
    status = "REVIEW_REQUIRED";
  } else {
    status = "NON_COMPLIANT";
  }

  return {
    frameworkId: framework.id,
    shortName: framework.shortName,
    status,
    relevantFlags: relevantFlags.length,
    relevantHFlags,
  };
}

/**
 * Compute FrameworkResults for all four frameworks.
 * Returns an array in registry order.
 */
export function computeAllFrameworkResults(
  unverifiedCount: number,
  governanceFlags: Array<{ category: string; severity: "H" | "M" | "L" }>
): FrameworkResult[] {
  return ALL_FRAMEWORKS.map((f) =>
    computeFrameworkResult(f, unverifiedCount, governanceFlags)
  );
}

/**
 * Parse and validate framework ids from upload (`JSON.stringify` array) or programmatic callers.
 * Unknown ids dropped; empty after filter → all frameworks (registry order).
 */
export function normalizeSelectedFrameworkIds(input: unknown): string[] {
  let raw: unknown[] = [];
  if (input == null || input === "") {
    return ALL_FRAMEWORKS.map((f) => f.id);
  }
  if (typeof input === "string") {
    try {
      const parsed = JSON.parse(input) as unknown;
      raw = Array.isArray(parsed) ? parsed : [];
    } catch {
      return ALL_FRAMEWORKS.map((f) => f.id);
    }
  } else if (Array.isArray(input)) {
    raw = input;
  }
  const asStrings = raw.filter((x): x is string => typeof x === "string").map((s) => s.trim());
  const unique = Array.from(new Set(asStrings)).filter((id) => id in FRAMEWORK_MAP);
  if (unique.length === 0) {
    return ALL_FRAMEWORKS.map((f) => f.id);
  }
  return ALL_FRAMEWORKS.filter((f) => unique.includes(f.id)).map((f) => f.id);
}

/** Score only the frameworks the user selected for this deal (subset of `ALL_FRAMEWORKS` order). */
export function computeFrameworkResultsForSelection(
  frameworkIds: string[],
  unverifiedCount: number,
  governanceFlags: Array<{ category: string; severity: "H" | "M" | "L" }>
): FrameworkResult[] {
  return frameworkIds
    .map((id) => FRAMEWORK_MAP[id])
    .filter((f): f is ComplianceFramework => f != null)
    .map((fw) => computeFrameworkResult(fw, unverifiedCount, governanceFlags));
}
